DATABASE_URI: mysql+pymysql://saas1:yoshi2003@35.232.151.129/saas1
Database engine created successfully
Database tables created successfully
 * Serving Flask app 'main_test'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.11.7:8080
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 126-254-817
127.0.0.1 - - [31/May/2025 17:50:32] "GET /health HTTP/1.1" 200 -
127.0.0.1 - - [31/May/2025 17:50:58] "POST /save HTTP/1.1" 200 -
127.0.0.1 - - [31/May/2025 17:51:06] "GET /customers HTTP/1.1" 200 -
127.0.0.1 - - [31/May/2025 17:56:08] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [31/May/2025 17:56:08] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
127.0.0.1 - - [31/May/2025 17:56:19] "GET / HTTP/1.1" 200 -
 * Detected change in '/Users/yoshifumikoide/Desktop/myapp/main.py', reloading
DATABASE_URI: mysql+pymysql://saas1:yoshi2003@35.232.151.129/saas1
Database engine created successfully
Database tables created successfully
Received data: {'newCustomerName': '„ÉÜ„Çπ„Éà‰ºöÁ§æ', 'newCustomerPlan': 'starter', 'newCustomerMrr': '30000', 'newCustomerAssignee': 'Áî∞‰∏≠Â§™ÈÉé', 'newCustomerInitialFee': '100000', 'newCustomerOperationFee': '50000', 'newCustomerHours': '10', 'newCustomerRegion': 'Èñ¢Êù±', 'newCustomerIndustry': 'IT', 'newCustomerChannel': 'WebÊ§úÁ¥¢'}
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 126-254-817
 * Detected change in '/Users/yoshifumikoide/Desktop/myapp/main.py', reloading
DATABASE_URI: mysql+pymysql://saas1:yoshi2003@35.232.151.129/saas1
Database engine created successfully
Database tables created successfully
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 126-254-817
 * Detected change in '/Users/yoshifumikoide/Desktop/myapp/main.py', reloading
DATABASE_URI: mysql+pymysql://saas1:yoshi2003@35.232.151.129/saas1
Database engine created successfully
Database tables created successfully
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 126-254-817
127.0.0.1 - - [31/May/2025 22:01:39] "GET /customers HTTP/1.1" 200 -
127.0.0.1 - - [31/May/2025 22:01:51] "GET /customers HTTP/1.1" 200 -
 * Detected change in '/Users/yoshifumikoide/Desktop/myapp/main.py', reloading
DATABASE_URI: mysql+pymysql://saas1:yoshi2003@35.232.151.129/saas1
Database engine created successfully
Database tables created successfully
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 126-254-817
127.0.0.1 - - [31/May/2025 22:40:51] "GET /customers HTTP/1.1" 200 -
127.0.0.1 - - [31/May/2025 22:41:06] "GET /customers HTTP/1.1" 200 -
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/multiprocessing/resource_tracker.py:301: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown: {'/mp-r56soled'}
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/multiprocessing/resource_tracker.py:301: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown: {'/mp-kngwxq_b'}
  warnings.warn(
